# Global configuration for ananicy-cpp
check_freq = 15
loglevel = info
log_applied_rule = false

# Enable/disable features
apply_nice = true
apply_sched = true
apply_ionice = true
apply_oom_score_adj = true
apply_latnice = true
apply_cpuset = true

# Module loading
type_load = true
rule_load = true
cgroup_load = true
cgroup_realtime_workaround = true
